# Generated by Django 5.2.4 on 2025-11-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='encrypted_master_key',
            field=models.TextField(blank=True, help_text="User's master encryption key, encrypted by CLI", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='key_salt',
            field=models.TextField(blank=True, help_text='Salt for deriving password-based key to unwrap master key', max_length=64, null=True),
        ),
    ]
