# Generated by Django 5.2.4 on 2026-01-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_encrypted_master_key_alter_user_key_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encrypted_private_key',
            field=models.TextField(blank=True, help_text="User's private key encrypted with their derived user_key (only they can decrypt)", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(blank=True, help_text="User's public key for encrypting workspace keys (others can encrypt for this user)", null=True),
        ),
    ]
