# Generated by Django 5.2.4 on 2026-01-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_encrypted_private_key_user_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='encrypted_master_key',
        ),
        migrations.AlterField(
            model_name='user',
            name='key_salt',
            field=models.TextField(blank=True, help_text='Salt for deriving user_key from password', max_length=64, null=True),
        ),
    ]
