# Generated by Django 5.2.4 on 2026-05-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_encrypted_master_key_alter_user_key_salt'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_date',
            field=models.DateField(blank=True, help_text='The last date the user was active on the platform (UTC date only)', null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_active_date'], name='accounts_us_last_ac_088c77_idx'),
        ),
    ]
