# Generated by Django 5.2.4 on 2026-05-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_active_date_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_last_ac_088c77_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_active_date',
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(blank=True, help_text='The last time the user was active on the platform (UTC)', null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_active_at'], name='accounts_us_last_ac_28fb1f_idx'),
        ),
    ]
