# Generated by Django 5.2.4 on 2026-09-03 19:37

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_billing_id'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='billing_id',
            field=models.CharField(blank=True, default=apps.accounts.models.generate_billing_id, help_text='Mandatory AgentSecrets Cloud billing & entitlement identifier', max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['billing_id'], name='accounts_us_billing_f59059_idx'),
        ),
    ]
