# Generated by Django 5.2.4 on 2026-08-21 07:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0012_clouddelegationkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('free', 'Free Developer'), ('pro_monthly', 'Pro Monthly ($7/mo)'), ('pro_yearly', 'Pro Annual ($60/yr)')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('price_cents', models.IntegerField(default=0, help_text='Price in USD cents')),
                ('billing_interval', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=20)),
                ('included_events', models.BigIntegerField(default=10000, help_text='Included monthly events & resolution calls')),
                ('log_retention_days', models.IntegerField(default=3, help_text='Days of historical audit logs retained')),
                ('included_seats', models.IntegerField(default=3, help_text='Team member seats included in base price')),
                ('extra_seat_price_cents', models.IntegerField(default=200, help_text='Price in USD cents per extra seat ($2.00)')),
                ('external_plan_id', models.CharField(blank=True, help_text='Gateway Plan Code (e.g. Paystack PLN_xxx)', max_length=100, null=True)),
            ],
            options={
                'db_table': 'billing_plans',
                'ordering': ['price_cents'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('provider_type', models.CharField(choices=[('dummy', 'Dummy / Local Sandbox'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('dodo', 'Dodo Payments'), ('polar', 'Polar.sh'), ('custom', 'Custom Gateway')], default='dummy', max_length=30)),
                ('external_customer_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('external_subscription_id', models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('spend_cap_dollars', models.IntegerField(default=20, help_text='Hard monthly spend limit in USD')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_subscriptions',
                'indexes': [models.Index(fields=['workspace', 'status'], name='workspace_s_workspa_c2917e_idx'), models.Index(fields=['external_customer_id'], name='workspace_s_externa_2f55a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceUsageRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('billing_period_start', models.DateField(db_index=True)),
                ('billing_period_end', models.DateField(db_index=True)),
                ('event_count', models.BigIntegerField(default=0, help_text='Total secret resolution & workload boot events')),
                ('overage_units_billed', models.IntegerField(default=0, help_text='Number of 50k overage blocks billed')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_usage_records',
                'indexes': [models.Index(fields=['workspace', 'billing_period_start'], name='workspace_u_workspa_48707e_idx')],
                'unique_together': {('workspace', 'billing_period_start')},
            },
        ),
    ]
