# Generated by Django 5.2.4 on 2025-11-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secret',
            options={'ordering': ['key']},
        ),
        migrations.AlterUniqueTogether(
            name='secret',
            unique_together={('project', 'key')},
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['project', 'key'], name='secrets_project_7c6a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['project', '-updated_at'], name='secrets_project_bca680_idx'),
        ),
        migrations.AlterModelTable(
            name='secret',
            table='secrets',
        ),
    ]
