# Generated by Django 5.2.4 on 2026-01-02 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secret',
            options={'ordering': ['key']},
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_owner_i_2301d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_owner_i_fcc2dc_idx',
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this project belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='secret',
            unique_together={('project', 'key')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'name'], name='projects_workspa_0c6753_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', '-created_at'], name='projects_workspa_afc2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['project', 'key'], name='secrets_project_7c6a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['project', '-updated_at'], name='secrets_project_bca680_idx'),
        ),
        migrations.AlterModelTable(
            name='secret',
            table='secrets',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
