# Generated by Django 5.2.4 on 2026-01-02 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0002_alter_secret_options_and_more'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('workspace', 'name')},
        ),
    ]
