# Generated by Django 5.2.4 on 2026-03-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0003_alter_project_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secret',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='secret',
            name='environment',
            field=models.CharField(default='development', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='secret',
            unique_together={('project', 'environment', 'key')},
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['project', 'environment'], name='secrets_project_0c5f5a_idx'),
        ),
    ]
