# Generated by Django 5.2.4 on 2026-06-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0004_alter_secret_unique_together_secret_environment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='policy',
            field=models.JSONField(blank=True, default=dict, help_text='Usage policy: allowed domains and HTTP methods'),
        ),
    ]
