# Generated by Django 5.2.4 on 2026-08-27 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0005_secret_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who initially added this secret', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_secrets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secret',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this secret', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_secrets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['project', 'updated_by'], name='secrets_project_007bc6_idx'),
        ),
    ]
