# Generated by Django 5.2.4 on 2025-12-30 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('shared', 'Shared')], default='shared', help_text='personal = auto-created on signup, shared = team/project sharing', max_length=20)),
                ('owner', models.ForeignKey(help_text='The user who created/owns this workspace', on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('read_only', 'Read Only')], default='member', help_text='Role determines what actions the user can perform', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited')], default='active', help_text='active = full access, invited = pending acceptance', max_length=20)),
                ('encrypted_workspace_key', models.TextField(help_text="Workspace key encrypted with this user's public key")),
                ('user', models.ForeignKey(help_text='The user who is a member of the workspace', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'memberships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', '-created_at'], name='workspaces_owner_i_04a3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['type'], name='workspaces_type_2e589a_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'status'], name='memberships_user_id_b0e170_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['workspace', 'role'], name='memberships_workspa_70ed64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'workspace')},
        ),
    ]
