# Generated by Django 5.2.4 on 2026-03-03 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspaceallowlistlog_workspaceallowlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workspaceallowlistlog',
            index=models.Index(fields=['workspace', '-performed_at'], name='workspaces__workspa_d522e2_idx'),
        ),
    ]
