# Generated by Django 5.2.4 on 2026-03-08 17:09

import apps.workspaces.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0003_alter_project_unique_together'),
        ('workspaces', '0003_workspaceallowlistlog_workspaces__workspa_d522e2_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRegistration',
            fields=[
                ('id', models.CharField(default=apps.workspaces.models.generate_areg_id, editable=False, max_length=31, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable agent name', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Project this agent is registered to (if project-scoped)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='secrets_app.project')),
                ('workspace', models.ForeignKey(help_text='Workspace this agent is registered to', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'agent_registrations',
            },
        ),
        migrations.CreateModel(
            name='AgentToken',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(help_text='HMAC-SHA256 of the raw token value', max_length=64)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_tokens', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='workspaces.agentregistration')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tokens', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'agent_tokens',
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.CharField(default=apps.workspaces.models.generate_log_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('schema_version', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('agent_id', models.CharField(blank=True, max_length=64, null=True)),
                ('identity_level', models.CharField(choices=[('anonymous', 'Anonymous'), ('declared', 'Declared'), ('issued', 'Issued')], default='anonymous', max_length=20)),
                ('credential_ref', models.CharField(max_length=255)),
                ('injection_style', models.CharField(max_length=50)),
                ('target_domain', models.CharField(max_length=253)),
                ('target_url', models.TextField()),
                ('target_path', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField()),
                ('proxy_duration_ms', models.IntegerField(default=0)),
                ('redacted', models.BooleanField(default=False)),
                ('redaction_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('resolution_path', models.CharField(max_length=50)),
                ('allowlist_snapshot', models.JSONField(default=dict)),
                ('caller_role', models.CharField(max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_snapshot_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('agent_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='workspaces.agenttoken')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='secrets_app.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='agentregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('workspace', 'name'), name='unique_workspace_agent_name'),
        ),
        migrations.AddConstraint(
            model_name='agentregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'name'), name='unique_project_agent_name'),
        ),
    ]
