# Generated by Django 5.2.4 on 2026-03-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0003_alter_project_unique_together'),
        ('workspaces', '0004_agentregistration_agenttoken_auditlogentry_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['workspace', '-timestamp'], name='audit_logs_workspa_79841a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['agent_token', '-timestamp'], name='audit_logs_agent_t_f5c27c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['target_domain', '-timestamp'], name='audit_logs_target__b22145_idx'),
        ),
    ]
