# Generated by Django 5.2.4 on 2026-03-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_auditlogentry_audit_logs_workspa_79841a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttoken',
            name='environment',
            field=models.CharField(default='development', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='environment',
            field=models.CharField(blank=True, default='development', max_length=20, null=True),
        ),
    ]
