# Generated by Django 5.2.4 on 2026-05-19 21:34

import apps.workspaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_agenttoken_environment_auditlogentry_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='id',
            field=models.CharField(default=apps.workspaces.models.generate_log_id, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
