# Generated by Django 5.2.4 on 2026-06-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_increase_audit_id_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentregistration',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict, help_text='Agent capability restrictions'),
        ),
    ]
