# Generated by Django 5.2.4 on 2026-06-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_agentregistration_capabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentregistration',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict, help_text='Agent capability restrictions', null=True),
        ),
    ]
