# Generated by Django 5.2.4 on 2026-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_alter_agentregistration_capabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttoken',
            name='token_hash',
            field=models.CharField(db_index=True, help_text='SHA-256 of the raw token value', max_length=64, unique=True),
        ),
    ]
