# Generated by Django 5.2.4 on 2026-08-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_alter_agenttoken_token_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='identity_level',
            field=models.CharField(choices=[('anonymous', 'Anonymous'), ('declared', 'Declared'), ('issued', 'Issued'), ('user', 'User')], default='anonymous', max_length=20),
        ),
    ]
