# Generated by Django 5.2.4 on 2026-08-21 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_alter_auditlogentry_identity_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudDelegationKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolver_name', models.CharField(default='default', help_text='Name or identifier of the cloud resolver cluster', max_length=100)),
                ('public_key', models.CharField(help_text='X25519 public key hex string of the cloud resolver (CEDK_pub)', max_length=64)),
                ('sealed_workspace_key', models.TextField(blank=True, help_text='Base64-encoded NaCl SealedBox ciphertext containing the workspace DEK', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this delegation is currently active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration timestamp for the delegation', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Timestamp when delegation was revoked', null=True)),
                ('workspace', models.ForeignKey(help_text='Workspace this delegation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='delegation_keys', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'cloud_delegation_keys',
                'indexes': [models.Index(fields=['workspace', 'is_active'], name='cloud_deleg_workspa_21eac1_idx'), models.Index(fields=['public_key'], name='cloud_deleg_public__392fc2_idx')],
            },
        ),
    ]
