# Generated by Django 5.2.4 on 2026-09-03 21:01

import apps.workspaces.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0005_secret_policy'),
        ('workspaces', '0012_clouddelegationkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicAuditLogEntry',
            fields=[
                ('id', models.CharField(default=apps.workspaces.models.generate_forensic_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('stream_id', models.CharField(db_index=True, default='default', help_text='Forensic log stream / session identifier', max_length=64)),
                ('stream_seq', models.BigIntegerField(default=0, help_text='Monotonically increasing sequence number in the stream')),
                ('prev_chain_hash', models.CharField(blank=True, default='', help_text='SHA-256 hash of the previous record in the stream', max_length=64)),
                ('chain_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hash linking this record into the cryptographic chain', max_length=64)),
                ('entry_hash', models.CharField(blank=True, default='', help_text='SHA-256 hash of the current record contents', max_length=64)),
                ('event_json', models.JSONField(blank=True, default=dict, help_text='Step 1: Event block (call type, key name, target domain, method, outcome, latency)')),
                ('snapshot_json', models.JSONField(blank=True, default=dict, help_text='Step 2: Snapshot block (workspace allowlist, project, capabilities at evaluation time)')),
                ('enforcement_json', models.JSONField(blank=True, default=dict, help_text='Step 3: Enforcement block (decision, decided_by, layers evaluated, failure reasons)')),
                ('resolution_json', models.JSONField(blank=True, default=dict, help_text='Step 4: Resolution block (injection style, redaction triggers, SSRF checks, status code)')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the event occurred')),
            ],
            options={
                'db_table': 'forensic_audit_logs',
                'ordering': ['stream_id', 'stream_seq', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceActivityLog',
            fields=[
                ('id', models.CharField(default=apps.workspaces.models.generate_act_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, default='', help_text='Email of the actor at the time of the action', max_length=255)),
                ('action', models.CharField(db_index=True, help_text='Type of action (e.g. secret.created, secret.deleted, project.created)', max_length=100)),
                ('target_type', models.CharField(blank=True, default='', help_text='Target entity type (e.g. secret, project, member)', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', help_text='Target entity identifier', max_length=255)),
                ('target_name', models.CharField(blank=True, default='', help_text='Target human-readable name (e.g. secret key or project name)', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Safe metadata describing the change (NEVER raw secret values)')),
                ('ip_address', models.CharField(blank=True, help_text='IP address of the caller', max_length=45, null=True)),
                ('source', models.CharField(default='api', help_text='Action source: web, cli, or api', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'workspace_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='source',
            field=models.CharField(choices=[('cloud', 'Cloud Resolver'), ('cli', 'CLI Local Proxy')], default='cloud', help_text='Source of the audit entry (Cloud Resolver or CLI Local Proxy)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['source', '-timestamp'], name='audit_logs_source_5bf8b7_idx'),
        ),
        migrations.AddField(
            model_name='forensicauditlogentry',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this forensic record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forensic_logs', to='secrets_app.project'),
        ),
        migrations.AddField(
            model_name='forensicauditlogentry',
            name='workspace',
            field=models.ForeignKey(help_text='Workspace this forensic record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='forensic_logs', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='workspaceactivitylog',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='User who initiated this action, if human', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceactivitylog',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project associated with this activity, if project-scoped', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='secrets_app.project'),
        ),
        migrations.AddField(
            model_name='workspaceactivitylog',
            name='workspace',
            field=models.ForeignKey(help_text='Workspace this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='forensicauditlogentry',
            index=models.Index(fields=['workspace', '-created_at'], name='forensic_au_workspa_2d24ae_idx'),
        ),
        migrations.AddIndex(
            model_name='forensicauditlogentry',
            index=models.Index(fields=['stream_id', 'stream_seq'], name='forensic_au_stream__025163_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceactivitylog',
            index=models.Index(fields=['workspace', '-created_at'], name='workspace_a_workspa_3374b3_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceactivitylog',
            index=models.Index(fields=['workspace', 'action', '-created_at'], name='workspace_a_workspa_6a182d_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceactivitylog',
            index=models.Index(fields=['target_type', 'target_id'], name='workspace_a_target__08b829_idx'),
        ),
    ]
