# Generated by Django 5.2.4 on 2026-09-04 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_forensicauditlogentry_workspaceactivitylog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='billing_id',
            field=models.CharField(blank=True, help_text='Dedicated billing ID for paid/detached workspace. If null, draws from owner.billing_id (free tier).', max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['billing_id'], name='workspaces_billing_882bc6_idx'),
        ),
    ]
