# Generated by Django 5.2.4 on 2026-09-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_workspace_billing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', help_text='free = draws from owner quota; pro = dedicated 100k quota', max_length=20),
        ),
    ]
