# Generated by Django 5.2.4 on 2026-04-30 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetricsAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users_daily', models.IntegerField(default=0)),
                ('active_users_weekly', models.IntegerField(default=0)),
                ('active_users_monthly', models.IntegerField(default=0)),
                ('new_signups', models.IntegerField(default=0)),
                ('total_projects', models.IntegerField(default=0)),
                ('total_secrets', models.IntegerField(default=0)),
                ('new_projects', models.IntegerField(default=0)),
                ('new_secrets', models.IntegerField(default=0)),
                ('total_workspaces', models.IntegerField(default=0)),
                ('shared_workspaces', models.IntegerField(default=0)),
                ('total_invites', models.IntegerField(default=0)),
                ('avg_members_per_workspace', models.FloatField(default=0.0)),
                ('total_proxy_calls', models.IntegerField(default=0)),
                ('total_proxy_blocked', models.IntegerField(default=0)),
                ('total_proxy_redacted', models.IntegerField(default=0)),
                ('command_usage', models.JSONField(default=dict, help_text='Aggregated command usage across all users for this day')),
                ('environment_distribution', models.JSONField(default=dict, help_text='Count of active environments across users {development: N, staging: N, production: N}')),
                ('integration_usage', models.JSONField(default=dict, help_text='Count of users per integration {mcp: N, proxy: N, env: N, sdk: N}')),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='daily_metri_date_c5278a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelemetrySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cli_version', models.CharField(blank=True, help_text='CLI version string (e.g. 0.4.2)', max_length=20, null=True)),
                ('os', models.CharField(blank=True, help_text='Operating system (e.g. darwin, linux, windows)', max_length=50, null=True)),
                ('arch', models.CharField(blank=True, help_text='Architecture (e.g. arm64, amd64)', max_length=20, null=True)),
                ('command_executions', models.JSONField(default=dict, help_text='Map of command name to execution count for this sync period')),
                ('active_environment', models.CharField(blank=True, help_text='Active environment at sync time (development/staging/production)', max_length=20, null=True)),
                ('workspace_type', models.CharField(blank=True, help_text='Type of active workspace (personal/shared)', max_length=20, null=True)),
                ('workspace_member_count', models.IntegerField(blank=True, help_text='Number of members in the active workspace', null=True)),
                ('project_secret_count', models.IntegerField(blank=True, help_text='Number of secrets in the active project', null=True)),
                ('proxy_calls', models.IntegerField(default=0, help_text='Total proxy credential injection calls in this period')),
                ('proxy_blocked', models.IntegerField(default=0, help_text='Proxy calls blocked by allowlist in this period')),
                ('proxy_redacted', models.IntegerField(default=0, help_text='Proxy responses where credentials were redacted')),
                ('injection_styles_used', models.JSONField(blank=True, default=list, help_text='List of injection styles used (bearer, header, query, basic, body_field, form_field)')),
                ('integrations_active', models.JSONField(blank=True, default=list, help_text='List of active integrations (mcp, openclaw, env, proxy, sdk)')),
                ('client_timestamp', models.DateTimeField(blank=True, help_text='Timestamp from the CLI when telemetry was generated', null=True)),
                ('user', models.ForeignKey(help_text='The user who sent this telemetry', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telemetry_snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='telemetry_s_user_id_7e922c_idx'), models.Index(fields=['-created_at'], name='telemetry_s_created_c44345_idx')],
            },
        ),
    ]
