# Generated by Django 5.2.4 on 2026-04-30 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrysnapshot',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who sent this telemetry (null if anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_snapshots', to=settings.AUTH_USER_MODEL),
        ),
    ]
