# Generated by Django 5.2.4 on 2026-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_alter_telemetrysnapshot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetricsaggregate',
            name='avg_projects_per_workspace',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailymetricsaggregate',
            name='avg_secrets_per_project',
            field=models.FloatField(default=0.0),
        ),
    ]
