# Generated by Django 5.2.4 on 2026-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_dailymetricsaggregate_avg_keychain_resolution_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetricsaggregate',
            name='total_policies',
            field=models.IntegerField(default=0),
        ),
    ]
