# Generated by Django 5.2.4 on 2026-09-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_add_total_policies_to_daily_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetricsaggregate',
            name='total_proxy_calls_cli',
            field=models.IntegerField(default=0, help_text='Total proxy calls originating from CLI instances'),
        ),
        migrations.AddField(
            model_name='dailymetricsaggregate',
            name='total_proxy_calls_cloud',
            field=models.IntegerField(default=0, help_text='Total direct resolve calls handled by Cloud Resolver'),
        ),
    ]
