# Generated by Django 5.2.4 on 2026-09-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_dailymetricsaggregate_total_proxy_calls_cli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetricsaggregate',
            name='alias_usage',
            field=models.JSONField(default=dict, help_text='Aggregated alias and shortcut usage across all users for this day'),
        ),
    ]
